config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :artists, only: [:index, :show]
  resources :releases, only: [:index, :show]
  resources :contacts, only: [:new, :create]
  get 'contacts/sent'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :releases
  has_many :bookings
  has_one_attached :avatar

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :performance, presence: true
  validates :city, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :artist

  validates :booking_date, presence: true
  validates :city, presence: true
  validates :promoter_name, presence: true
  validates :event_name, presence: true
  validates :email, format: { with: /\A.*@.*\.com\z/ }, presence: true
  validates :message, presence: true
  validates :amount_offered, presence: true, numericality: { only_integer: true }

  before_validation :remove_whitespaces

  private

  def remove_whitespaces
    email.strip! unless email.nil?
  end
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true, presence: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :category, validate: true, inclusion: { in: %w(Label Booking Autre), message: "%{value} is not valid" }
  attribute :message, validate: true

  def headers
    {
      to: "antoine.delprat.pro@gmail.com",
      subject: "Formulaire Contact CCR - Sujet #{category}",
      from: "antoine.delprat.pro@gmail.com",
      reply_to: %("#{name}" <#{email}>)
    }
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :cover

  validates :name, presence: true
  validates :date, presence: true
  validates :city, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :picture

  validates :name, presence: true
  validates :price, presence: true
end

app/models/release.rb
class Release < ApplicationRecord
  belongs_to :artist
  has_one_attached :photo

  validates :name, presence: true
  validates :release_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      redirect_to action: :sent
    else
      flash.now[:error] = 'Could not send message'
      render :new, status: :unprocessable_entity
    end
  end

  def sent
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  def index
    @releases = Release.all
  end

  def show
    @release = Release.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/artists/index.html.erb
<div id="main-artists">
  <div>
    <h1>Artistes</h1>
  </div>
  <div class="wrapper artists">
      <% array_sorted = @artists.sort_by { |x| x.name.downcase } %>
      <% array_sorted.each do |artist| %>
        <% if artist.name != 'Various Artists' && artist.name != 'DL-T' && artist.name != 'Alder' %>
          <%= link_to artist_path(artist.id) do %>
            <div class="artist-card d-flex justify-content-center align-items-center" style="background-image: url(<%= cl_image_path(artist.avatar.key) %>)">
                <div class="hover-card flex-grow-1 d-flex justify-content-center align-items-center">
                  <%=artist.name%>
                </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </div>
</div>

app/views/artists/show.html.erb
<% content_for :meta_title, "#{@artist.name} du label Cane Corso Records" %>
<% content_for :meta_description, @artist.description %>
<% content_for :meta_image, cl_image_path(@artist.avatar.key) if @artist.avatar.attached? %>

<div id="main-artist">
  <%= link_to "< retour", artists_path, class: "artist-back" %>
  <div id="artist-content">
    <img class="artist-picture" src="<%= cl_image_path(@artist.avatar.key) %>" alt="<%= @artist.name %>">
    <div class="artist-description">
      <h2><%= @artist.name %></h2>
      <p><%= @artist.description %></p>
    </div>
    <div class="artist-details">
      <div>
        <p class="artist-details-title">Performances</p>
        <p><%= @artist.performance %></p>
      </div>
      <div>
        <p class="artist-details-title">Labels</p>
        <p><%= @artist.label_list %></p>
      </div>
      <div>
        <p class="artist-details-title">Réseaux</p>
        <% if @artist.soundcloud_link != "" %>
          <p class="artist-links"><%= link_to "Soundcloud", @artist.soundcloud_link, target: "_blank" %></p>
        <% end %>
        <% if @artist.instagram_link != "" %>
          <p class="artist-links"><%= link_to "Instagram", @artist.instagram_link, target: "_blank" %></p>
        <% end %>
        <% if @artist.facebook_link != "" %>
          <p class="artist-links"><%= link_to "Facebook", @artist.facebook_link, target: "_blank" %></p>
        <% end %>
        <% if @artist.spotify_link != "" %>
          <p class="artist-links"><%= link_to "Spotify", @artist.spotify_link, target: "_blank" %></p>
        <% end %>
      </div>
      <div>
        <p class="artist-details-title">Ville</p>
        <p><%= @artist.city %></p>
      </div>
    </div>
    <% if @artist.video_link.include?("youtube") %>
      <div class="artist-video">
        <iframe width="480" height="270" src="<%= @artist.video_link %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      </div>
    <% elsif @artist.video_link.include?("soundcloud") %>
      <div class="artist-podcast">
        <iframe width="100%" height="180" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=<%= @artist.video_link %>&color=%23cd16eb&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
      </div>
    <% end %>
  </div>
  <% if @artist.name != 'Alder' %>
    <div id="artist-booking">
      <%= link_to "Booker cet artiste", new_contact_path, class: "artist-cta-main" %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div id="contact-form">
  <h1 class="title">Contacter Cane Corso Records</h1>
  <%= simple_form_for @contact do |f| %>
    <%= f.input :name, label: "Nom et prénom", placeholder: "David Ghetto" %>
    <%= f.input :email, label: "Votre email pour le suivi", placeholder: "david.ghetto@mail.com" %>
    <%= f.input :category, label: "Le motif de votre message", collection: ['Label', 'Booking', 'Autre'] %>
    <%= f.input :message, label: "Votre message", placeholder: "Bonjour, ...", as: :text %>
    <%= f.submit "Envoyer", class: "cta-send" %>
  <% end %>
</div>

app/views/contacts/sent.html.erb
<div id="contact-confirmation">
  <h1>Merci !</h1>
  <p>Votre message a été envoyé avec succès.</p>
  <p>Nous reviendrons vers vous dès que possible.</p>
  <div><%= link_to "Retourner à l'accueil", root_path, class: "back-cta-secondary" %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>

    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>">
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= meta_image %>">
    <meta property="og:description" content="<%= meta_description %>">
    <meta property="og:site_name" content="<%= meta_title %>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

  </head>

  <body>
    <%= render "shared/navbar"  %>
    <%= yield %>
    <%= render "shared/footer"  %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div id="main-home">
  <div id="home-picture">
    <div class="home-picture-hover">
      <h1>Agence de booking, label<br>& évènements.</h1>
    </div>
  </div>
  <div id="home-content">
    <div class="home-next">
      <div>
        <h2>Next Event</h2>
        <p>Rendez-vous le 23 Septembre prochain à Angers !</p>
        <p>Au programme : un Open Air gratuit de 14h à minuit dans le Parc Saint-Serge, avec des stands, de quoi manger, se rafraîchir...</p>
        <p>Côté son, Cane Corso Records invite du beau monde et notamment l'angevin Unklevon (Boys Noize Records) pour un set live.</p>
        <a class="home-event-cta" href="https://www.facebook.com/events/3554129824869242/" target="_blank">Accéder à l'évènement</a>
      </div>
      <a class="home-next-event" href="https://www.facebook.com/events/3554129824869242/" target="_blank"></a>
    </div>
    <div class="home-releases">

    </div>
  </div>
</div>

app/views/releases/index.html.erb
<div id="main-releases">
  <div>
    <h1>Releases</h1>
  </div>
  <div>
    <% @releases.each do |release| %>
      <div class="releases">
        <div class="releases-block">
          <%= link_to release_path(release.id) do %>
            <div class="releases-card" style="background-image: url(<%= cl_image_path(release.photo.key) %>)">
            </div>
            <div class="releases-infos">
              <%=release.name%><br>
              <%=release.artist.name%>
            </div>
          <% end %>
        </div>
        <div class="releases-players">
          <iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=<%= release.soundcloud_link %>&color=%23cd16eb&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/releases/show.html.erb
<% content_for :meta_title, "#{@release.artist.name} - #{@release.name}" %>
<% content_for :meta_description, "#{@release.artist.name} - #{@release.name} sorti sur le label Cane Corso Records" %>
<% content_for :meta_image, cl_image_path(@release.photo.key) if @release.photo.attached? %>

<div id="main-release">
  <%= link_to "< retour", releases_path, class: "release-back" %>
  <div id="release-content">
    <div>
      <div class="release-picture" style="background-image: url(<%= cl_image_path(@release.photo.key) %>)"></div>
      <div class="release-info">
        <p><%=@release.artist.name%> - <%=@release.name%></p>
        <p><%=@release.release_date%></p>
      </div>
    </div>
    <div class="release-player">
          <iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=<%= @release.soundcloud_link %>&color=%23cd16eb&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
    </div>
  </div>
  <div id="release-actions">
    <div><%= link_to "Acheter sur Bandcamp", @release.bandcamp_link, class: "release-cta-main", target: "_blank" %></div>
    <div><%= link_to "Écouter sur Spotify", @release.spotify_link, class: "release-cta-secondary", target: "_blank" %></div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer id="footer" class="text-center text-white" style="background-color: rgb(0 0 0);">
  <!-- Grid container -->
  <div class="container p-3 pb-0">
    <!-- Section: Social media -->
    <section class="mb-2">
      <a class="btn btn-floating m-1" href="https://www.instagram.com/canecorso.rec/" target="_blank" role="button"
        ><i class="fa-brands fa-instagram"></i
      ></a>
      <a class="btn btn-floating m-1" href="https://www.facebook.com/CaneCorsoRecords" target="_blank" role="button"
        ><i class="fa-brands fa-facebook-f"></i
      ></a>
      <a class="btn btn-floating m-1" href="https://soundcloud.com/canecorsorecords" target="_blank" role="button"
        ><i class="fa-brands fa-soundcloud"></i
      ></a>
      <a class="btn btn-floating m-1" href="https://canecorsorecords.bandcamp.com/" target="_blank" role="button"
        ><i class="fa-brands fa-bandcamp"></i
      ></a>
      <a class="btn btn-floating m-1" href="https://open.spotify.com/user/8l3mqiccmcs61ngdq5c05nu5a?si=88a48a914c4447e9" target="_blank" role="button"
        ><i class="fa-brands fa-spotify"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-2 pb-3" style="font-size: 10px;">
    © 2023 All rights reserved to Cane Corso Records. Website by Antoine Delprat.
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div id="logo"></div>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <%# <span class="navbar-toggler-icon"></span> %>
    <i class="fa-solid fa-bars"></i>
  </button>
  <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
    <ul class="navbar-nav links">
      <li class="nav-item active">
        <%= link_to "Releases", releases_path, class: "nav-link" %>
      </li>
      <%# <li class="nav-item">
        <a class="nav-link" href="#">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Shop</a>
      </li> %>
      <li class="nav-item">
        <%= link_to "Artistes", artists_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", new_contact_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav socials">
      <li class="nav-item active">
        <a class="nav-link" href="https://www.instagram.com/canecorso.rec/" target="_blank"><i class="fa-brands fa-instagram"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.facebook.com/CaneCorsoRecords" target="_blank"><i class="fa-brands fa-facebook-f"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://soundcloud.com/canecorsorecords" target="_blank"><i class="fa-brands fa-soundcloud"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://canecorsorecords.bandcamp.com/" target="_blank"><i class="fa-brands fa-bandcamp"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://open.spotify.com/user/8l3mqiccmcs61ngdq5c05nu5a?si=88a48a914c4447e9" target="_blank"><i class="fa-brands fa-spotify"></i></a>
      </li>
    </ul>
  </div>
</nav>